apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-06-21T07:42:51Z"
  labels:
    app: adder
  name: adder
  namespace: default
  resourceVersion: "1599"
  selfLink: /api/v1/namespaces/default/services/adder
  uid: cf52f7d0-b392-11ea-b9a6-0242b34812bf
spec:
  clusterIP: 10.98.206.237
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30875
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: adder
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 172.17.0.201
