apiVersion: v1
kind: Service
metadata:
  labels:
    app: source
  name: source
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30399
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: source
  sessionAffinity: None
  type: LoadBalancer
