apiVersion: v1
kind: Service
metadata:
  labels:
    app: suber
  name: suber
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30440
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: suber
  sessionAffinity: None
  type: LoadBalancer
